//! Application configuration — all driven from environment variables.
//!
//! Every setting has a sensible default. The PaaS orchestrator injects
//! APP_* environment variables when starting the process.

use std::collections::HashMap;

/// Configuration for a PaaS-hosted PHP application.
#[derive(Clone)]
pub struct AppConfig {
    /// Application name (for logging/metrics).
    pub app_name: String,
    /// Listen host (default: 0.0.0.0).
    pub host: String,
    /// Listen port (default: 8080).
    pub port: u16,
    /// Application root directory (document root parent).
    pub app_root: String,
    /// Entry script relative to app_root (default: public/index.php).
    pub entry_script: String,
    /// Document root for static files (default: public/).
    pub document_root: String,
    /// Number of PHP worker threads (default: CPU cores).
    pub workers: usize,
    /// PHP memory_limit per request (default: 128M).
    pub memory_limit: String,
    /// PHP max_execution_time per request in seconds (default: 30).
    pub max_execution_time: u64,
    /// Application environment (production, staging, development).
    pub app_env: String,
    /// Optional preload script (compiled on boot). Used by Phase 8.
    #[allow(dead_code)]
    pub preload: Option<String>,
    /// PHP INI overrides from APP_INI_* env vars.
    pub ini_overrides: HashMap<String, String>,
    /// Health check path (default: /_health).
    pub health_path: String,
    /// Readiness check path (default: /_ready).
    pub ready_path: String,
    /// Metrics path (default: /_metrics).
    pub metrics_path: String,
    /// Graceful shutdown timeout in seconds (default: 30). Used by Phase 3.
    #[allow(dead_code)]
    pub shutdown_timeout: u64,
    /// Static file extensions to serve directly.
    pub static_extensions: Vec<String>,
    /// Comma-separated list of disabled PHP functions (security blocklist).
    pub disable_functions: String,
    /// Whether to enable filesystem isolation via open_basedir.
    pub sandbox_enabled: bool,
    /// Path to a pre-compiled opcache file (generated by `php-rs-ctl build`).
    /// If present, VMs load this on startup to skip first-request compilation.
    pub opcache_path: Option<String>,
}

impl AppConfig {
    /// Build configuration from environment variables.
    pub fn from_env() -> Self {
        let workers = env_or("APP_WORKERS", "0")
            .parse::<usize>()
            .unwrap_or(0);
        let workers = if workers == 0 {
            std::thread::available_parallelism()
                .map(|n| n.get())
                .unwrap_or(4)
        } else {
            workers
        };

        // Collect APP_INI_* overrides.
        let mut ini_overrides = HashMap::new();
        for (key, value) in std::env::vars() {
            if let Some(ini_key) = key.strip_prefix("APP_INI_") {
                // Convert APP_INI_display_errors → display_errors
                // Convert APP_INI_session__save_path → session.save_path
                let ini_key = ini_key.replace("__", ".");
                ini_overrides.insert(ini_key, value);
            }
        }

        let static_extensions = env_or(
            "APP_STATIC_EXTENSIONS",
            "css,js,mjs,json,xml,png,jpg,jpeg,gif,webp,avif,svg,ico,woff,woff2,ttf,otf,eot,pdf,txt,map,mp3,mp4,webm,ogg,wav,zip,gz,tar,wasm",
        )
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();

        Self {
            app_name: env_or("APP_NAME", "php-app"),
            host: env_or("APP_HOST", "0.0.0.0"),
            port: env_or("APP_PORT", "8080").parse().unwrap_or(8080),
            app_root: env_or("APP_ROOT", "."),
            entry_script: env_or("APP_ENTRY", "public/index.php"),
            document_root: env_or("APP_DOCROOT", "public"),
            workers,
            memory_limit: env_or("APP_MEMORY_LIMIT", "128M"),
            max_execution_time: env_or("APP_MAX_EXECUTION_TIME", "30")
                .parse()
                .unwrap_or(30),
            app_env: env_or("APP_ENV", "production"),
            preload: std::env::var("APP_PRELOAD").ok(),
            ini_overrides,
            health_path: env_or("APP_HEALTH_PATH", "/_health"),
            ready_path: env_or("APP_READY_PATH", "/_ready"),
            metrics_path: env_or("APP_METRICS_PATH", "/_metrics"),
            shutdown_timeout: env_or("APP_SHUTDOWN_TIMEOUT", "30")
                .parse()
                .unwrap_or(30),
            static_extensions,
            disable_functions: env_or(
                "APP_DISABLE_FUNCTIONS",
                // Default security blocklist — dangerous functions disabled in PaaS.
                "exec,shell_exec,system,passthru,popen,proc_open,proc_close,\
                 proc_get_status,proc_nice,proc_terminate,\
                 pcntl_alarm,pcntl_exec,pcntl_fork,pcntl_signal,pcntl_waitpid,\
                 pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,\
                 pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,\
                 pcntl_signal_dispatch,pcntl_sigprocmask,pcntl_sigwaitinfo,\
                 pcntl_sigtimedwait,pcntl_async_signals,\
                 posix_kill,posix_mkfifo,posix_setuid,posix_setgid,posix_setsid,\
                 dl,putenv,apache_setenv,\
                 show_source,phpinfo",
            ),
            sandbox_enabled: env_or("APP_SANDBOX", "1") != "0",
            opcache_path: std::env::var("APP_OPCACHE").ok(),
        }
    }

    /// Resolve the entry script to an absolute path.
    pub fn entry_script_path(&self) -> std::path::PathBuf {
        let root = std::path::Path::new(&self.app_root);
        root.join(&self.entry_script)
    }

    /// Resolve the document root to an absolute path.
    pub fn document_root_path(&self) -> std::path::PathBuf {
        let root = std::path::Path::new(&self.app_root);
        root.join(&self.document_root)
    }

    /// Check if a file extension is a static asset.
    pub fn is_static_extension(&self, ext: &str) -> bool {
        self.static_extensions.iter().any(|e| e.eq_ignore_ascii_case(ext))
    }

    /// Parse memory_limit string (e.g. "128M") into bytes.
    pub fn memory_limit_bytes(&self) -> usize {
        parse_size(&self.memory_limit)
    }

    /// Build the open_basedir string for filesystem isolation.
    /// Restricts PHP to the app root, /tmp, and system temp directory.
    pub fn open_basedir(&self) -> String {
        if !self.sandbox_enabled {
            return String::new(); // No restriction.
        }

        let root = std::path::Path::new(&self.app_root);
        let abs_root = root.canonicalize()
            .unwrap_or_else(|_| root.to_path_buf());

        let mut paths = vec![abs_root.to_string_lossy().to_string()];

        // Allow /tmp for session files and temporary data.
        paths.push("/tmp".to_string());

        // Allow system temp dir if different from /tmp.
        let sys_tmp = std::env::temp_dir();
        let sys_tmp_str = sys_tmp.to_string_lossy().to_string();
        if sys_tmp_str != "/tmp" && !paths.contains(&sys_tmp_str) {
            paths.push(sys_tmp_str);
        }

        paths.join(":")
    }
}

fn env_or(key: &str, default: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| default.to_string())
}

fn parse_size(val: &str) -> usize {
    let val = val.trim();
    if val.is_empty() {
        return 0;
    }
    let (num_str, multiplier) = match val.as_bytes().last() {
        Some(b'K' | b'k') => (&val[..val.len() - 1], 1024usize),
        Some(b'M' | b'm') => (&val[..val.len() - 1], 1024 * 1024),
        Some(b'G' | b'g') => (&val[..val.len() - 1], 1024 * 1024 * 1024),
        _ => (val, 1),
    };
    num_str.trim().parse::<usize>().unwrap_or(0) * multiplier
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_size() {
        assert_eq!(parse_size("128M"), 128 * 1024 * 1024);
        assert_eq!(parse_size("2G"), 2 * 1024 * 1024 * 1024);
        assert_eq!(parse_size("64K"), 64 * 1024);
        assert_eq!(parse_size("1024"), 1024);
        assert_eq!(parse_size(""), 0);
    }

    #[test]
    fn test_is_static_extension() {
        let config = AppConfig::from_env();
        assert!(config.is_static_extension("css"));
        assert!(config.is_static_extension("JS"));
        assert!(config.is_static_extension("png"));
        assert!(!config.is_static_extension("php"));
    }

    #[test]
    fn test_disable_functions_default() {
        let config = AppConfig::from_env();
        // Default blocklist should include exec, shell_exec, system, etc.
        assert!(config.disable_functions.contains("exec"));
        assert!(config.disable_functions.contains("shell_exec"));
        assert!(config.disable_functions.contains("system"));
        assert!(config.disable_functions.contains("passthru"));
        assert!(config.disable_functions.contains("proc_open"));
        assert!(config.disable_functions.contains("dl"));
        assert!(config.disable_functions.contains("putenv"));
    }

    #[test]
    fn test_sandbox_enabled_by_default() {
        let config = AppConfig::from_env();
        assert!(config.sandbox_enabled);
    }

    #[test]
    fn test_open_basedir_contains_app_root() {
        let config = AppConfig::from_env();
        let basedir = config.open_basedir();
        // Should contain /tmp at minimum.
        assert!(basedir.contains("/tmp"));
        // Should be colon-separated paths.
        assert!(basedir.contains(":"));
    }
}
