//! Git push deployment — bare repos with post-receive hooks.
//!
//! Flow:
//! 1. `php-rs-ctl git init <app>` — creates bare repo at ~/.php-rs/repos/{app}.git
//! 2. User adds remote: `git remote add phprs ~/.php-rs/repos/{app}.git`
//!    or `git remote add phprs ssh://user@host/~/.php-rs/repos/{app}.git`
//! 3. `git push phprs main` triggers the post-receive hook
//! 4. Hook checks out code → runs build → deploys
//!
//! The post-receive hook is a shell script that calls `php-rs-ctl` commands.

use std::path::{Path, PathBuf};

/// Initialize a bare git repo for an app with a post-receive deploy hook.
pub fn init_repo(app_name: &str, repos_dir: &Path) -> Result<PathBuf, String> {
    let repo_path = repos_dir.join(format!("{}.git", app_name));

    if repo_path.exists() {
        return Err(format!(
            "Git repo already exists at {}",
            repo_path.display()
        ));
    }

    // Create the bare repo.
    let status = std::process::Command::new("git")
        .args(["init", "--bare"])
        .arg(&repo_path)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map_err(|e| format!("Failed to run git init: {}", e))?;

    if !status.success() {
        return Err("git init --bare failed".into());
    }

    // Install the post-receive hook.
    let hooks_dir = repo_path.join("hooks");
    std::fs::create_dir_all(&hooks_dir)
        .map_err(|e| format!("Cannot create hooks dir: {}", e))?;

    let hook_path = hooks_dir.join("post-receive");
    let hook_script = generate_post_receive_hook(app_name);
    std::fs::write(&hook_path, hook_script)
        .map_err(|e| format!("Cannot write post-receive hook: {}", e))?;

    // Make the hook executable.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(&hook_path, perms)
            .map_err(|e| format!("Cannot set hook permissions: {}", e))?;
    }

    Ok(repo_path)
}

/// Remove the bare git repo for an app.
pub fn remove_repo(app_name: &str, repos_dir: &Path) -> Result<(), String> {
    let repo_path = repos_dir.join(format!("{}.git", app_name));
    if repo_path.exists() {
        std::fs::remove_dir_all(&repo_path)
            .map_err(|e| format!("Cannot remove repo: {}", e))?;
    }
    Ok(())
}

/// Get the path to an app's bare git repo.
pub fn repo_path(app_name: &str, repos_dir: &Path) -> PathBuf {
    repos_dir.join(format!("{}.git", app_name))
}

/// Check if a repo exists for an app.
pub fn repo_exists(app_name: &str, repos_dir: &Path) -> bool {
    repo_path(app_name, repos_dir).exists()
}

/// Generate the post-receive hook script.
fn generate_post_receive_hook(app_name: &str) -> String {
    // Find the php-rs-ctl binary path at hook time.
    // The hook reads stdin for ref updates, checks out the pushed code,
    // builds a slug, and deploys it.
    format!(
        r#"#!/bin/sh
#
# post-receive hook for php-rs PaaS deployment
# Auto-generated by php-rs-ctl git init
#

APP_NAME="{app_name}"
echo ""
echo "=====> Deploying $APP_NAME..."
echo ""

# Read the pushed ref.
while read OLDREV NEWREV REFNAME; do
    BRANCH=$(echo "$REFNAME" | sed 's|refs/heads/||')
    echo "-----> Branch: $BRANCH ($OLDREV -> $NEWREV)"

    # Only deploy from main/master by default.
    case "$BRANCH" in
        main|master)
            ;;
        *)
            echo "       Skipping non-deploy branch: $BRANCH"
            continue
            ;;
    esac

    # Create a temporary checkout directory.
    CHECKOUT_DIR=$(mktemp -d)
    echo "-----> Checking out code..."
    GIT_WORK_TREE="$CHECKOUT_DIR" git checkout -f "$NEWREV" 2>/dev/null

    # Find php-rs-ctl binary.
    CTL=$(command -v php-rs-ctl 2>/dev/null || echo "php-rs-ctl")

    # Build the slug.
    echo "-----> Building..."
    BUILD_OUTPUT_DIR=$(mktemp -d)
    if $CTL build "$CHECKOUT_DIR" --name "$APP_NAME" --output "$BUILD_OUTPUT_DIR" 2>&1; then
        SLUG="$BUILD_OUTPUT_DIR/$APP_NAME.tar.gz"
        if [ -f "$SLUG" ]; then
            echo "-----> Deploying slug..."
            $CTL deploy "$APP_NAME" --tar "$SLUG" 2>&1
            echo "=====> Deployed $APP_NAME successfully!"
        else
            echo "       ERROR: Slug not found at $SLUG"
            echo "       Build may have failed."
        fi
    else
        echo "       ERROR: Build failed!"
    fi

    # Clean up.
    rm -rf "$CHECKOUT_DIR" "$BUILD_OUTPUT_DIR"
done

echo ""
echo "=====> Deploy complete."
echo ""
"#,
        app_name = app_name
    )
}

/// Get the default repos directory.
pub fn default_repos_dir() -> PathBuf {
    let state_dir = std::env::var("PHPRS_STATE_DIR").unwrap_or_else(|_| {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        format!("{}/.php-rs", home)
    });
    let dir = PathBuf::from(state_dir).join("repos");
    let _ = std::fs::create_dir_all(&dir);
    dir
}

/// List all git repos.
pub fn list_repos(repos_dir: &Path) -> Vec<String> {
    let mut repos = Vec::new();
    if let Ok(entries) = std::fs::read_dir(repos_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".git") && entry.path().is_dir() {
                repos.push(name[..name.len() - 4].to_string());
            }
        }
    }
    repos.sort();
    repos
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static COUNTER: AtomicU64 = AtomicU64::new(0);

    fn test_repos_dir() -> PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "phprs-git-test-{}-{}",
            std::process::id(),
            n
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_init_repo() {
        let dir = test_repos_dir();
        let repo = init_repo("myapp", &dir).unwrap();

        assert!(repo.exists());
        assert!(repo.join("HEAD").exists()); // Bare repo has HEAD.
        assert!(repo.join("hooks/post-receive").exists());

        // Hook should be executable.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = std::fs::metadata(repo.join("hooks/post-receive"))
                .unwrap()
                .permissions();
            assert!(perms.mode() & 0o111 != 0);
        }

        // Hook should contain app name.
        let hook = std::fs::read_to_string(repo.join("hooks/post-receive")).unwrap();
        assert!(hook.contains("myapp"));
        assert!(hook.contains("post-receive hook"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_init_repo_already_exists() {
        let dir = test_repos_dir();
        init_repo("existing", &dir).unwrap();

        // Second init should fail.
        let result = init_repo("existing", &dir);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("already exists"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_remove_repo() {
        let dir = test_repos_dir();
        init_repo("removable", &dir).unwrap();
        assert!(repo_exists("removable", &dir));

        remove_repo("removable", &dir).unwrap();
        assert!(!repo_exists("removable", &dir));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_remove_nonexistent_repo() {
        let dir = test_repos_dir();
        // Should not error on nonexistent repo.
        remove_repo("nonexistent", &dir).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_repo_exists() {
        let dir = test_repos_dir();
        assert!(!repo_exists("nope", &dir));
        init_repo("exists", &dir).unwrap();
        assert!(repo_exists("exists", &dir));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_list_repos() {
        let dir = test_repos_dir();
        assert!(list_repos(&dir).is_empty());

        init_repo("alpha", &dir).unwrap();
        init_repo("beta", &dir).unwrap();
        init_repo("gamma", &dir).unwrap();

        let repos = list_repos(&dir);
        assert_eq!(repos, vec!["alpha", "beta", "gamma"]);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_repo_path() {
        let dir = PathBuf::from("/tmp/repos");
        let path = repo_path("myapp", &dir);
        assert_eq!(path, PathBuf::from("/tmp/repos/myapp.git"));
    }

    #[test]
    fn test_post_receive_hook_content() {
        let hook = generate_post_receive_hook("testapp");
        assert!(hook.contains("APP_NAME=\"testapp\""));
        assert!(hook.contains("php-rs-ctl"));
        assert!(hook.contains("git checkout"));
        assert!(hook.contains("main|master"));
        assert!(hook.starts_with("#!/bin/sh"));
    }
}
